# Generated by Django 4.0.4 on 2024-04-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infopage', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('hora_nacimiento', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
                ('situacion_sentimental', models.CharField(max_length=20)),
                ('pensamientos', models.CharField(max_length=20)),
                ('elemento', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('email_usuario', models.EmailField(blank=True, max_length=254, null=True)),
                ('carga', models.CharField(max_length=50)),
            ],
        ),
    ]
