# Generated by Django 4.0.4 on 2024-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitud',
            field=models.FloatField(default=4.711),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitud',
            field=models.FloatField(default=-74.0721),
        ),
    ]
